project:
  type: website
  render:
    - reports/analysis.qmd
    - reports/vrsummit.qmd

website:
  title: "Vista Teleportation"
  navbar:
    left:
      - href: reports/analysis.qmd
        text: Analysis
      - href: reports/vrsummit.qmd
        text: VR Summit

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true